package siscalci;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import static siscalci.TelaInicial.translate;

public class Funcao1 extends javax.swing.JFrame {

    private String valor;
    private int contadorDireita = 1, contadorEsquerda = -9;
    private double a, b, raiz; //Declaração das Variáveis da Função de 1º Grau Valores de A, Constante e Raíz
    private double xDireita = 0, yDireita = 0, xEsquerda = 0, yEsquerda = 0, incremento = 1;

    public Funcao1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblFuncao2 = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        txtA1 = new javax.swing.JTextField();
        lblB1 = new javax.swing.JLabel();
        txtB1 = new javax.swing.JTextField();
        lblRaiz1 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnCalcular1 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnGrafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Função de 1º Grau");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Função 1º Grau");

        lblFuncao2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lblFuncao2.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncao2.setText("Y = ax + b");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFuncao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFuncao2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblA1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        lblA1.setText("A =");

        txtA1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtA1KeyPressed(evt);
            }
        });

        lblB1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        lblB1.setText("B =");

        txtB1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtB1KeyPressed(evt);
            }
        });

        lblRaiz1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        lblRaiz1.setText("Raíz = ");

        lblResultado.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        btnCalcular1.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcular1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btnCalcular1.setText("Calcular");
        btnCalcular1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });
        btnCalcular1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCalcular1KeyPressed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnVoltarKeyPressed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        btnLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLimparKeyPressed(evt);
            }
        });

        btnGrafico.setBackground(new java.awt.Color(255, 255, 255));
        btnGrafico.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btnGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/grafico_icone_30x30.png"))); // NOI18N
        btnGrafico.setText("Gerar Grafico");
        btnGrafico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnGrafico))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRaiz1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblA1)
                        .addComponent(txtA1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtB1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblB1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRaiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVoltar)
                        .addComponent(btnGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void validarTxt() {
        ((AbstractDocument) txtA1.getDocument()).setDocumentFilter(new RandomValidator(10, true, false, false, false, '.', '-'));
        ((AbstractDocument) txtA1.getDocument()).setDocumentFilter(new RandomValidator(10, true, false, false, false, '.', '-'));

        /* Na ordem: 

         Número máximo de caracteres 
         Permite números 
         Valida ponto flutuante (1.50, por exemplo) 
         Permite letras 
         Permite todos os caracteres especias 
         Caracteres especiais permitidos (pode passar quantos quiser como parâmetro, note que no exemplo permite '.' e '-'
         */
    }

    public void validarCampoVazio() {
        if (txtA1.getText().trim().isEmpty() && !txtB1.getText().trim().isEmpty()) {
            if (translate == true) {
                JOptionPane.showMessageDialog(null, "Assuming value of 1 to A!", "Message", JOptionPane.INFORMATION_MESSAGE);
                txtA1.setText(String.valueOf(1d));
            } else {
                JOptionPane.showMessageDialog(null, "Assumindo o valor de 1 para A!");
                txtA1.setText(String.valueOf(1d));
            }

        } else if (txtB1.getText().trim().isEmpty() && !txtA1.getText().trim().isEmpty()) {
            if (translate == true) {
                JOptionPane.showMessageDialog(null, "Assuming value of 1 to B!", "Message", JOptionPane.INFORMATION_MESSAGE);
                txtB1.setText(String.valueOf(1d));
            } else {
                JOptionPane.showMessageDialog(null, "Assumindo o valor de 1 para B!");
                txtB1.setText(String.valueOf(1d));
            }
        } else if (txtA1.getText().trim().isEmpty() && txtB1.getText().trim().isEmpty()) {
            if (translate == true) {
                JOptionPane.showMessageDialog(null, "Assuming value of 1 to A and B!", "Message", JOptionPane.INFORMATION_MESSAGE);
                txtA1.setText(String.valueOf(1d));
                txtB1.setText(String.valueOf(1d));
            } else {
                JOptionPane.showMessageDialog(null, "Assumindo o valor de 1 para A e B!");
                txtA1.setText(String.valueOf(1d));
                txtB1.setText(String.valueOf(1d));
            }
        }
    }

    public void calculaFuncao() {
        btnLimpar.setVisible(true);
        btnGrafico.setVisible(true);
        pack();
        setLocationRelativeTo(null);

        validarCampoVazio();

        a = Double.parseDouble(txtA1.getText().trim());
        b = Double.parseDouble(txtB1.getText().trim());

        while (a == 0) {
            if (a == 0) {
                if (translate == true) {
                    valor = JOptionPane.showInputDialog(null, "'a' can't be 0. Type another value.", "Data Entry", JOptionPane.ERROR_MESSAGE);
                    a = Double.parseDouble(valor.trim());
                    txtA1.setText(String.valueOf(a));
                } else {
                    valor = JOptionPane.showInputDialog("'a' não pode ser 0. Insira outro valor.");
                    a = Double.parseDouble(valor.trim());
                    txtA1.setText(String.valueOf(a));
                }
            }
        }
        raiz = -b / a;

        lblResultado.setText(String.valueOf(raiz));
    }

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        calculaFuncao();
        validarTxt();
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtA1.setText("");
        txtB1.setText("");
        lblResultado.setText("");
        btnLimpar.setVisible(false);
        btnGrafico.setVisible(false);
        pack();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new OpcaoFuncao().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        /**
         *
         * @author Jonas
         * @Modified by Roger Trevizan
         */

//        raiz = Double.parseDouble(lblResultado.getText());
//        b = Double.parseDouble(txtB1.getText());

        if ((b * 1 + raiz) < 1) {
            if ((b * 1 + raiz) < 0.5) {
                incremento = 0.1;
            } else {
                incremento = 0.5;
            }
        } else {
            incremento = 1;
        }

        XYSeries series = new XYSeries("Linha");

        while (contadorDireita <= 10) {
            yDireita = b * xDireita + raiz;
            series.add(xDireita, yDireita);
            xDireita = xDireita + incremento;
            contadorDireita++;
        }

        while (contadorEsquerda <= 0) {
            yEsquerda = b * xEsquerda + raiz;
            series.add(xEsquerda, yEsquerda);
            xEsquerda = xEsquerda - incremento;
            contadorEsquerda++;
        }

        XYDataset xyDataset = new XYSeriesCollection(series);
        JFreeChart chart = ChartFactory.createXYLineChart("Gráfico da Função " + a + "x" + " + " + "( " + b + " )", "X", "Y", xyDataset, PlotOrientation.VERTICAL, true, true, false);
        ChartFrame frame1 = new ChartFrame("Gráfico de Funções", chart);
        frame1.setSize(600, 600);
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame1.setLocation((tela.width - frame1.getSize().width) / 2,
                (tela.height - frame1.getSize().height) / 2);
        frame1.setVisible(true);

//         txtA1.setEditable(false);
//         txtB1.setEditable(false);
//         btGerar1.setEnabled(false);
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void btnCalcular1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCalcular1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaFuncao();
            validarTxt();
        }
    }//GEN-LAST:event_btnCalcular1KeyPressed

    private void btnVoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new OpcaoFuncao().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnVoltarKeyPressed

    private void btnLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtA1.setText("");
            txtB1.setText("");
            lblResultado.setText("");
            btnLimpar.setVisible(false);
            btnGrafico.setVisible(false);
            pack();
        }
    }//GEN-LAST:event_btnLimparKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if (translate == true) {
            setTitle("1st Degree Function");
            lblTitulo1.setText("1st Degree Function");
            lblRaiz1.setText("Result");
            btnCalcular1.setText("Calculate");
            btnVoltar.setText("Return");
            btnLimpar.setText("Clean");
            btnGrafico.setText("Generate Chart");
            pack();
            translate = true;
        }

        btnLimpar.setVisible(false);
        btnGrafico.setVisible(false);
        validarTxt();
        pack();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formComponentShown

    private void txtA1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtA1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaFuncao();
            validarTxt();
        }
    }//GEN-LAST:event_txtA1KeyPressed

    private void txtB1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtB1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaFuncao();
            validarTxt();
        }
    }//GEN-LAST:event_txtB1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Derivadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Derivadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Derivadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Derivadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcao1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblFuncao2;
    private javax.swing.JLabel lblRaiz1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextField txtA1;
    private javax.swing.JTextField txtB1;
    // End of variables declaration//GEN-END:variables

}
