package siscalci;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static siscalci.TelaInicial.translate;

public class Sobre extends javax.swing.JFrame {

    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbImagemIcone = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btCreditos = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbSoftware = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSobre = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        lbTituloIcone = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sobre o Programa");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lbImagemIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calculo_bc_150x300.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbImagemIcone)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImagemIcone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btCreditos.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btCreditos.setText("Créditos");
        btCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreditosActionPerformed(evt);
            }
        });
        btCreditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btCreditosKeyPressed(evt);
            }
        });

        btFechar.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btFechar.setText("Fechar");
        btFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        btFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btFecharKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btFechar)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreditos)
                    .addComponent(btFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbSoftware.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lbSoftware.setText(" Software de Cálculo Diferencial Integral I");

        txtSobre.setColumns(20);
        txtSobre.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        txtSobre.setRows(5);
        txtSobre.setText("  Copyright © 2015 - Desenvolvedores. Todos os direitos\nreservados.\n\n   Este é um Software de Código Aberto.\n Desenvolvido para fins educacionais. Venda proibida.\n\nVersão 1.0");
        jScrollPane1.setViewportView(txtSobre);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        lbTituloIcone.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N
        lbTituloIcone.setForeground(new java.awt.Color(51, 51, 51));
        lbTituloIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/about_icon_50x50.png"))); // NOI18N

        lbTitulo.setFont(new java.awt.Font("Cambria Math", 1, 28)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Sobre o Programa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbTituloIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTituloIcone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lbSoftware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if (translate == true) {
            lbTitulo.setText("About the Software");
            lbSoftware.setText("Calculus Differential and Integral I System");
            txtSobre.setText("  Copyright © 2015 - Developers. All rights reserved."
                    + "\n\n   This is an Open Source Software.\n Designed for educational purposes. Sale prohibited.\n\nVersão 1.0");
            btCreditos.setText("Credits");
            btFechar.setText("Close");
        }

        txtSobre.setEditable(false);
        pack();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formComponentShown

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btFecharKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_btFecharKeyPressed

    private void btCreditosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btCreditosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (translate == true) {
                JOptionPane.showMessageDialog(null, "<html>Development Team: <br><br>"
                        + "<br>* Pedro Henrique Omena Vieira: Software's Review and Translation . "
                        + "<br>* Roger de Oliveira Trevizan: Software's Analysis and Development."
                        + "<br>* Thaynara Alves da Silva: Software's Documentation, Design and Final Review."
                        + "<br><br><br> All the collaborators are, currently, graduating "
                        + "at 2nd Semester of the Systems Analisys and Development by Faculdade de Tecnologia de Americana - SP.",
                        "Sobre os Desenvolvedores", JOptionPane.WARNING_MESSAGE,
                        new ImageIcon("D:/Roger Documentos/Documents/NetBeansProjects/SisCalc1/src/Imagens/desenvolvedores_icone_150x150.png"));
            } else {
                JOptionPane.showMessageDialog(null, "<html>Equipe de Desenvolvimento: <br><br>"
                        + "<br>* Pedro Henrique Omena Vieira: Revisão e Tradução do Software. "
                        + "<br>* Roger de Oliveira Trevizan: Análise e Implementação do Software."
                        + "<br>* Thaynara Alves da Silva: Documentação, Design e Revisão Final do Software."
                        + "<br><br><br> Todos os colaboradores, atualmente, são graduandos "
                        + "no 2º Semestre de Análise e Desenvolvimento de Sistemas pela Faculdade de Tecnologia de Americana - SP.",
                        "Sobre os Desenvolvedores", JOptionPane.WARNING_MESSAGE,
                        new ImageIcon("D:/Roger Documentos/Documents/NetBeansProjects/SisCalc1/src/Imagens/desenvolvedores_icone_150x150.png"));
            }
        }
    }//GEN-LAST:event_btCreditosKeyPressed

    private void btCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreditosActionPerformed
        if (translate == true) {
            JOptionPane.showMessageDialog(null, "<html>Development Team: <br><br>"
                    + "<br> Pedro Henrique Omena Vieira: Software's Review and Translation.<br>"
                    + "<br> Roger de Oliveira Trevizan: Software's Analysis and Development.<br>"
                    + "<br> Thaynara Alves da Silva: Software's Documentation, Design and Final Review.<br>"
                    + "<br><br><br> All the collaborators are, currently, graduating "
                    + "at 2nd Semester of the Systems Analisys and Development by Faculdade de Tecnologia de Americana - SP.",
                    "Sobre os Desenvolvedores", JOptionPane.WARNING_MESSAGE,
                    new ImageIcon("D:/Roger Documentos/Documents/NetBeansProjects/SisCalc1/src/Imagens/desenvolvedores_icone_150x150.png"));
        } else {
            JOptionPane.showMessageDialog(null, "<html>Equipe de Desenvolvimento: <br><br>"
                    + "<br> Pedro Henrique Omena Vieira: Revisão e Tradução do Software.<br>"
                    + "<br> Roger de Oliveira Trevizan: Análise e Desenvolvimento do Software.<br>"
                    + "<br> Thaynara Alves da Silva: Documentação, Design e Revisão Final do Software.<br>"
                    + "<br><br><br> Todos os colaboradores, atualmente, são graduandos "
                    + "no 2º Semestre de Análise e Desenvolvimento de Sistemas pela Faculdade de Tecnologia de Americana - SP.", 
                    "Sobre os Desenvolvedores", JOptionPane.PLAIN_MESSAGE,
                    new ImageIcon("D:/Roger Documentos/Documents/NetBeansProjects/SisCalc1/src/Imagens/desenvolvedores_icone_150x150.png"));
        }
    }//GEN-LAST:event_btCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreditos;
    private javax.swing.JButton btFechar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImagemIcone;
    private javax.swing.JLabel lbSoftware;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloIcone;
    private javax.swing.JTextArea txtSobre;
    // End of variables declaration//GEN-END:variables
}
